Ddr 39 create rule/how to page
Australian-DDR-Events/aus-ddr-poc pull request #33
Opened 2021-01-31 03:57 UTC by alexissyp

2021-01-31 11:16 UTC, nhivn requested changes
This looks great!
I've checked out your branch to view the new page on the browser as well.
One small nitpick from me is that the Step and the Button (at the bottom) are like flushed against the edges. It'd be awesome if you can add some padding (if you want).
Otherwise, there is only that 1 little import and the merge conflict that you'll need to resolve 😄

2021-01-31 11:16 UTC, nhivn commented on src/components/router/index.tsx
> +import HowTo from '~/features/how-to';
Please import as `feature/how-to` 😄

2021-01-31 11:39 UTC, alexissyp commented on src/components/router/index.tsx
> +import HowTo from '~/features/how-to';
Sorry. Will do.

2021-02-01 09:47 UTC, alexissyp commented on src/features/how-to/components/step-3/styled.ts
> +export const List = styled.ul``;
Yes, but I have since changed to using List from ant design instead.

2021-02-01 10:46 UTC, nhivn submitted a review, later dismissed

2021-02-01 10:46 UTC, nhivn commented on src/features/how-to/components/step-3/styled.ts
> +export const List = styled.ul``;
I think it should be removed if we aren't using it. Please feel free to remove this as a part of one of your other pull request. I don't want this to be block of the how to page release :D

2021-02-01 13:31 UTC, nhivn approved these changes

2021-02-01 13:31 UTC, merged